#!/bin/sh

set -e

account=$(gcloud auth list --format 'value(account)')
auth_info=$(gcloud auth describe "$account" --format "value[separator=','](token,expiry.date())")

password=$(echo "$auth_info" | cut -d',' -f1)
expiry_date=$(echo "$auth_info" | cut -d',' -f2)

time_to_expire_in_secs=$(($(date -d "$expiry_date" "+%s") - $(date "+%s")))

if [ $time_to_expire_in_secs -le 1 ]; then
  exit 1
fi

cat <<EOF
{
  "kind": "CredentialProviderResponse",
  "apiVersion": "credentialprovider.kubelet.k8s.io/v1alpha1",
  "cacheKeyType": "Registry",
  "cacheDuration": "${time_to_expire_in_secs}s",
  "auth": {
    "*.pkg.dev": { "username": "_dcgcloud_token", "password": "$password" },
    "pkg.dev": { "username": "_dcgcloud_token", "password": "$password" }
  }
}
EOF
